meetup/force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <label>Meetup</label>
    <nameField>
        <label>Meetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

meetup/force-app/main/default/objects/Meetup__c/fields/RegistrationCode__c.field-meta.xml
<CustomField>
    <fullName>RegistrationCode__c</fullName>
    <description>The code used to register for a meetup.</description>
    <label>Registration Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

meetup/force-app/main/default/objects/Meetup__c/fields/RegistrationLimit__c.field-meta.xml
<CustomField>
    <fullName>RegistrationLimit__c</fullName>
    <description>The maximum number of individuals able to register for a meetup.</description>
    <label>Registration Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

meetup/force-app/main/default/objects/Meetup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the meetup.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

meetup/force-app/main/default/classes/RegistrationPageController.cls
public with sharing class RegistrationPageController {
    @AuraEnabled
    public static Meetup__c getMeetup(String registrationCode) {
        try {
            List<Meetup__c> meetups = [
                SELECT Id, RegistrationLimit__c, Status__c, RegistrationCode__c
                FROM Meetup__c
                WHERE RegistrationCode__c = :registrationCode AND Status__c = :Constants.MEETUP_STATUS_OPENED
            ];

            return !meetups.isEmpty() ? meetups[0] : null;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}