meetup/force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <label>Meetup</label>
    <nameField>
        <label>Meetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

meetup/force-app/main/default/objects/Meetup__c/fields/RegistrationCode__c.field-meta.xml
<CustomField>
    <fullName>RegistrationCode__c</fullName>
    <description>The code used to register for a meetup.</description>
    <label>Registration Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

meetup/force-app/main/default/classes/Meetups.cls
public with sharing class Meetups {
    List<Meetup__c> meetups;

    public Meetups(List<Meetup__c> meetups) {
        this.meetups = meetups;
    }

    public void onBeforeInsert() {        
        this.setRegistrationCodes();
    }

    private void setRegistrationCodes() {
        for (Meetup__c m : this.meetups) {
            m.RegistrationCode__c = Utility.generateRandomString(8);
        }
    }
}