meetup/force-app/main/default/objects/Meetup__c/Meetup__c.object-meta.xml
<CustomObject>
    <label>Meetup</label>
    <nameField>
        <label>Meetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

meetup/force-app/main/default/objects/Meetup__c/fields/RegistrationLimit__c.field-meta.xml
<CustomField>
    <fullName>RegistrationLimit__c</fullName>
    <description>The maximum number of individuals able to register for a meetup.</description>
    <label>Registration Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

meetup/force-app/main/default/objects/Meetup__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the meetup.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

meetup/force-app/main/default/objects/MeetupRegistration__c/MeetupRegistration__c.object-meta.xml
<CustomObject>
    <label>Meetup Registration</label>
    <nameField>
        <displayFormat>RN-{000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetup Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

meetup/force-app/main/default/objects/MeetupRegistration__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>The email of the individual registered for the meetup.</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

meetup/force-app/main/default/objects/MeetupRegistration__c/fields/Meetup__c.field-meta.xml
<CustomField>
    <fullName>Meetup__c</fullName>
    <description>The meetup record with which the registration is associated.</description>
    <label>Meetup</label>
    <referenceTo>Meetup__c</referenceTo>
    <relationshipLabel>Meetup Registrations</relationshipLabel>
    <relationshipName>Meetup_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

meetup/force-app/main/default/classes/MeetupRegistrations.cls
public with sharing class MeetupRegistrations {
    List<MeetupRegistration__c> registrations;

    public MeetupRegistrations(List<MeetupRegistration__c> registrations) {
        this.registrations = registrations;
    }

    public void onAfterInsert() {        
        this.checkMeetupLimits();
    }

    public void onBeforeInsert() {        
        this.validateMeetupStatus();
        this.validateEmailAddress();

    }

    private void checkMeetupLimits() {
        Set<Id> meetupIds = new Set<Id>();
        for (MeetupRegistration__c mr : this.registrations) {
            meetupIds.add(mr.Meetup__c);
        }

        List<Meetup__c> meetupsToClose = new List<Meetup__c>();
        for (Meetup__c m : this.getMeetupsWithRegistrations(meetupIds)) {
            if (this.meetupShouldBeClosed(m)) {
                m.Status__c = Constants.MEETUP_STATUS_CLOSED;
                meetupsToClose.add(m);
            }
        }

        if (!meetupsToClose.isEmpty()) {
            update meetupsToClose;
        }
    }

    private void validateMeetupStatus() {
        Map<Id, List<MeetupRegistration__c>> registrationsByMeetupId = new Map<Id, List<MeetupRegistration__c>>();
        for (MeetupRegistration__c mr : this.registrations) {
            if (!registrationsByMeetupId.containsKey(mr.Meetup__c)) {
                registrationsByMeetupId.put(mr.Meetup__c, new List<MeetupRegistration__c>());
            }
            registrationsByMeetupId.get(mr.Meetup__c).add(mr);
        }

        List<Meetup__c> meetups = [SELECT Id, Status__c FROM Meetup__c WHERE Id IN:registrationsByMeetupId.keySet()];
        for (Meetup__c m : meetups) {
            if (m.Status__c == Constants.MEETUP_STATUS_CLOSED) {
                List<MeetupRegistration__c> registrations = registrationsByMeetupId.get(m.Id);
                for (MeetupRegistration__c mr : registrations) {
                    mr.addError(Constants.MEETUP_CLOSED_ERROR);
                }
            }
        }
    }

    private void validateEmailAddress() {
        Map<Id, List<MeetupRegistration__c>> registrationsByMeetupId = new Map<Id, List<MeetupRegistration__c>>();
        for (MeetupRegistration__c mr : this.registrations) {
            if (!registrationsByMeetupId.containsKey(mr.Meetup__c)) {
                registrationsByMeetupId.put(mr.Meetup__c, new List<MeetupRegistration__c>());
            }
            registrationsByMeetupId.get(mr.Meetup__c).add(mr);
        }

        Map<Id, List<String>> emails = new Map<Id, List<String>>();
        List<MeetupRegistration__c> invalidEmailRegistrations = new List<MeetupRegistration__c>();
        for (Meetup__c m : this.getMeetupsWithRegistrations(registrationsByMeetupId.keySet())) {
            for (MeetupRegistration__c mr : m.Meetup_Registrations__r) {
                if (!emails.containsKey(mr.Meetup__c)) {
                    emails.put(mr.Meetup__c, new List<String>());
                }
                emails.get(mr.Meetup__c).add(mr.Email__c);
            }
        }

        for (MeetupRegistration__c mr : this.registrations) {
            List<String> relatedEmails = emails.get(mr.Meetup__c);
            if (relatedEmails.contains(mr.Email__c)) {
                mr.addError(Constants.MEETUP_EMAIL_ERROR);
            }
        }
    }

    private List<Meetup__c> getMeetupsWithRegistrations(Set<Id> meetupIds) {
        return [SELECT Id, RegistrationLimit__c, Status__c, (SELECT Id, Email__c, Meetup__c FROM Meetup_Registrations__r) FROM Meetup__c WHERE Id IN :meetupIds];
    }

    private Boolean meetupShouldBeClosed(Meetup__c m) {
        return m.Meetup_Registrations__r.size() == m.RegistrationLimit__c && m.Status__c == Constants.MEETUP_STATUS_OPENED;
    }
}